### ISSUE TITLE
Fetch errors for crate from git link and  version

### ISSUE THREAD

**Issue by izderadicka** [serayuzgur/crates#36]
**Describe the bug**
With this dependency:
```
simple-file-cache = {git="https://github.com/izderadicka/simple-file-cache.git", features=["asynch"], version="0.1.2", optional=true}
```

extension show error (Fetch errors: simple-file-cache) after each change in Cargo.toml. 
Problem here is that dependency is now only in git, not yet in crates.io.
cargo tool is OK with it, just using available dependency from git.
(I think it's same as in documentation where dependency has both path and version keys)

**To Reproduce**
Add the dependency above to your Cargo.toml

**Expected behavior**
I think in this case it should ignore error from crates.io - not to show error notification and "Crates completed with errors on status bar" as this is a legitimate situation. cargo tool is also OK about it. 

**Screenshots**

Here is error stacktrace from dev console:
```
/usr/share/code/resources/app/out/vs/workbench/workbench.main.js:294 [Extension Host] StatusCodeError: 404 - "{\"errors\":[{\"detail\":\"Not Found\"}]}"
	at new StatusCodeError (/home/ivan/.vscode/extensions/serayuzgur.crates-0.3.5/node_modules/request-promise-core/lib/errors.js:32:15)
	at Request.plumbing.callback (/home/ivan/.vscode/extensions/serayuzgur.crates-0.3.5/node_modules/request-promise-core/lib/plumbing.js:104:33)
	at Request.RP$callback [as _callback] (/home/ivan/.vscode/extensions/serayuzgur.crates-0.3.5/node_modules/request-promise-core/lib/plumbing.js:46:31)
	at Request.self.callback (/home/ivan/.vscode/extensions/serayuzgur.crates-0.3.5/node_modules/request/request.js:185:22)
	at emitTwo (events.js:126:13)
	at Request.emit (events.js:214:7)
	at Request.<anonymous> (/home/ivan/.vscode/extensions/serayuzgur.crates-0.3.5/node_modules/request/request.js:1161:10)
	at emitOne (events.js:116:13)
	at Request.emit (events.js:211:7)
	at IncomingMessage.<anonymous> (/home/ivan/.vscode/extensions/serayuzgur.crates-0.3.5/node_modules/request/request.js:1083:12)
	at Object.onceWrapper (events.js:313:30)
	at emitNone (events.js:111:20)
	at IncomingMessage.emit (events.js:208:7)
	at endReadableNT (_stream_readable.js:1056:12)
	at _combinedTickCallback (internal/process/next_tick.js:138:11)
	at process._tickCallback (internal/process/next_tick.js:180:9)
```
and error notification:
![screenshot](https://user-images.githubusercontent.com/2185733/49685034-b7e83e00-fadc-11e8-9a77-b71cdf960f35.png)

**Desktop (please complete the following information):**
 - Linux, VS Code 1.19.1,  Crates ext. v. 0.3.5

**Comment by serayuzgur** [comment]
Same with #31

**Comment by serayuzgur** [comment]
Hi @izderadicka please check 0.3.6

**Comment by izderadicka** [comment]
Thanks
